### ISSUE TITLE
staked0 on CL

### ISSUE THREAD

**Issue by maxisvk** [velodrome-finance/sugar#82]
how or why the staked0 returns always 0 in CL positions?

**Comment by stas** [comment]
Hey @maxisvk 
your statement is false, please review the implementation and if you have questions, I'm happy to help with these:
https://github.com/velodrome-finance/sugar/blob/v3/contracts/LpSugar.vy#L774-L775

For any non dev-related question, please use the project Discord. This is not a forum.

Thank you.
