### ISSUE TITLE
execution reverted

### ISSUE THREAD

**Issue by maxisvk** [velodrome-finance/sugar#94]
error execution reverted when call function all for index 995

_limit (uint256) = 1
_offset (uint256) = 995
 tuple[] Error: Returned error: execution reverted

also tokens function 
   _offset (uint256) = 995
   _limit (uint256) = 2
give errors while 
   _offset (uint256) = 995
   _limit (uint256) = 1
or
  _offset (uint256) = 996
   _limit (uint256) = 1
works

**Comment by fringlesinthestreet** [comment]
Same issue here

**Comment by stas** [comment]
Apologies for delay with this issue, we've patched it quickly, feel free to use the addresses in the env files and in the PR if needed.

**Comment by Brovmos** [comment]
> error execution reverted when call function all for index 995
> 
> 
> 
> _limit (uint256) = 1
> 
> _offset (uint256) = 995
> 
>  tuple[] Error: Returned error: execution reverted
> 
> 
> 
> also tokens function 
> 
>    _offset (uint256) = 995
> 
>    _limit (uint256) = 2
> 
> give errors while 
> 
>    _offset (uint256) = 995
> 
>    _limit (uint256) = 1
> 
> or
> 
>   _offset (uint256) = 996
> 
>    _limit (uint256) = 1
> 
> works
> 
> 

Hello @maxisvk have you been able to resolve the issue?

**Comment by stas** [comment]
Apologies for the delay, the OP Mainnet and Base releases can be found here
https://github.com/velodrome-finance/sugar/blob/v3/env.optimism
https://github.com/velodrome-finance/sugar/blob/v3/env.base
